#name: End-to-end tests and automatic release
#
#on:
#  push:
#    branches:
#      - main # adjust this if you're working with a different branch
#
#jobs:
#  e2e_tests_and_release:
#    runs-on: ubuntu-latest
#
#    steps:
#      # Step 1: Checkout code
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      # Step 2: Run Cypress tests
#      - name: Cypress run
#        uses: cypress-io/github-action@v5
#        with:
#          start: npm start
#          wait-on: 'http://localhost:3000'
#
#      # Step 3: Upload Cypress artifacts (screenshots on failure)
#      - uses: actions/upload-artifact@v3
#        if: failure()
#        with:
#          name: cypress-screenshots
#          path: cypress/screenshots
#          if-no-files-found: ignore
#
#      # Step 4: Upload Cypress artifacts (videos on failure)
#      - uses: actions/upload-artifact@v3
#        if: failure()
#        with:
#          name: cypress-videos
#          path: cypress/videos
#          if-no-files-found: ignore
#
#      # Step 5: Setup Node.js
#      - name: Setup Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: '16'
#
#      # Step 6: Install dependencies
#      - name: Install dependencies
#        run: npm install
#
#      # Step 7: Get version from package.json
#      - name: Get version
#        id: package_version
#        run: |
#          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
#
#      # Step 8: Create Release (only if Cypress tests are successful)
#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ env.version }}
#          release_name: Release ${{ env.version }}
#          draft: false
#          prerelease: false
#        if: success() # Only create a release if the Cypress tests are successful
#
#      # Step 9: Output release URL (only if release created successfully)
#      - name: Output release URL
#        run: echo "Release URL is ${{ steps.create_release.outputs.html_url }}"
#        if: success() # Only show the release URL if the release was created successfully
